-- ============================================================
-- 用户管理模块 - 用户表
-- 兼容: H2、MySQL 8.0+、PostgreSQL 12+
-- ============================================================

CREATE TABLE IF NOT EXISTS users (
    -- ===================== 基本信息 =====================
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(50)  NOT NULL,
    email       VARCHAR(100) NOT NULL,
    password    VARCHAR(255) NOT NULL,

    -- ===================== 审计字段 =====================
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- ===================== 软删除字段 =====================
    deleted     SMALLINT   NOT NULL DEFAULT 0
);

-- 用户名唯一索引
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username ON users(username);

-- 邮箱唯一索引
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users(email);
